# Generated by Django 3.0.8 on 2020-07-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangodb', '0002_home_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='passwd',
            field=models.CharField(max_length=50),
        ),
    ]
